<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Nina - Story</title>
    <? include('head.php');?>
    <link rel="stylesheet" href="styles/story.css"/>
</head>
<body>

<? include('header.php');?>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <p>Image goes here</p>
        </div>
        <div class="col-sm-8">
            <p>WHEN I WAS LITTLE I USED TO GO TO THIS INCREDIBLE ICE CREAM AND CAKE PARLOUR CALLED DEL-REY IN THE SOUTH OF FRANCE. EVER SINCE I HAVE BEEN LUSTING AFTER ITS HOMEMADE DELICACIES HOPING TO DISCOVER DESSERTS THAT MIGHT COME CLOSE TO BEING EVEN HALF AS DELICIOUS.</p>
            <p>SO AFTER I LEFT UNIVERSITY I JOINED THE TEAM AT L'ANIMA, LONDON AS A COMMIS CHEF AND THIS IS WHERE MY PUDDING OBSESSION DEVELOPED FURTHER. WHILST WORKING IN PASTRY I FELL IN LOVE WITH THEIR STYLE OF COOKING USING FRESH ITALIAN INGREDIENTS WITH A RUSTIC TOUCH.</p>
            <p>NEXT, I SPENT TIME IN SOME REALLY FANTASTIC KITCHENS: FROM PREPARING MOELLEUX AU CHOCOLAT AT THE DORCHESTER FOR ALAIN DUCASSE, TARTE TATAIN AT TOM AIKENS, FRESH MARSHMALLOWS AT THE LEDBURY, AMARETTI AT LOCANDA LOCATELLI TO EVEN ROLLING OUT THE CROISSANT DOUGH AT 5AM IN THE SENEQUIER BAKERY, ST TROPEZ.</p>
            <p>LATER I WENT TO WORK AS THE CHEF FOR BOCCA DI LUPO'S GELUPO IN SOHO. THE QUALITY OF THEIR HOMEMADE GELATO AND SORBET WAS BEYOND ANY OTHER IN LONDON (EVEN WINNING TIME OUT'S "BEST GELATERIA" DURING MY TIME THERE).</p>
            <p>IT IS DRAWING FROM THESE EXPERIENCES THAT I AM LAUNCHING "NINA", A DESSERT COMPANY DEDICATED TO BRINGING A LITTLE TASTE OF MY CHILDHOOD FROM THE SOUTH OF FRANCE TO THE HEART OF LONDON AND BEYOND.</p>
        </div>
    </div>
</div>
<? include('footer.php'); ?>

</body>
</html>